import { NextResponse } from "next/server";
import { prisma } from "@/lib/db";

export async function GET(req: Request, { params }: { params: Promise<{ id: string }> }) {
    try {
        const { id: scanId } = await params;

        // 1. Fetch scan mission data
        const scan = await prisma.scan.findUnique({
            where: { id: scanId },
            include: {
                findings: true
            }
        });

        if (!scan) {
            return NextResponse.json({ error: "Mission not found" }, { status: 404 });
        }

        // 2. Generate Markdown Report
        const report = generateMarkdown(scan);

        // 3. Stream as File Download
        return new Response(report, {
            headers: {
                "Content-Type": "text/markdown",
                "Content-Disposition": `attachment; filename="sentinel-report-${scanId.substring(0, 8)}.md"`,
            },
        });
    } catch (error: any) {
        console.error("Report generation failure:", error);
        return NextResponse.json({ error: "Failed to generate report" }, { status: 500 });
    }
}

function generateMarkdown(scan: any) {
    const date = new Date(scan.createdAt).toLocaleString();
    const severityCount = {
        CRITICAL: scan.findings.filter((f: any) => f.severity === "CRITICAL").length,
        HIGH: scan.findings.filter((f: any) => f.severity === "HIGH").length,
        MEDIUM: scan.findings.filter((f: any) => f.severity === "MEDIUM").length,
        LOW: scan.findings.filter((f: any) => f.severity === "LOW").length,
    };

    let md = `# SENTINEL AI - Security Audit Report\n\n`;
    md += `## 1. Executive Summary\n`;
    md += `| Attribute | Details |\n`;
    md += `| :--- | :--- |\n`;
    md += `| **Target URL** | ${scan.url} |\n`;
    md += `| **Mission Date** | ${date} |\n`;
    md += `| **Mission Status** | ${scan.status} |\n`;
    md += `| **Mission ID** | ${scan.id} |\n\n`;

    md += `### Vulnerability Distribution\n`;
    md += `- **Critical**: ${severityCount.CRITICAL}\n`;
    md += `- **High**: ${severityCount.HIGH}\n`;
    md += `- **Medium**: ${severityCount.MEDIUM}\n`;
    md += `- **Low**: ${severityCount.LOW}\n\n`;

    md += `---\n\n`;
    md += `## 2. Technical Findings\n\n`;

    if (scan.findings.length === 0) {
        md += `*No significant vulnerabilities were identified during this mission.*\n\n`;
    } else {
        scan.findings.forEach((finding: any, index: number) => {
            md += `### [${index + 1}] ${finding.type} (${finding.severity})\n`;
            md += `**Category**: ${finding.location}\n\n`;
            md += `#### Analysis:\n${finding.description}\n\n`;
            md += `#### Evidence:\n\`\`\`\n${finding.evidence}\n\`\`\`\n\n`;
            md += `#### Remediation Roadmap:\n${finding.remediation || "Follow industry standard security best practices to mitigate this risk."}\n\n`;
            md += `---\n\n`;
        });
    }

    md += `## 3. Mission Logs (Telemetry)\n\n`;
    md += `\`\`\`\n`;
    scan.logs.forEach((log: string) => {
        md += `${log}\n`;
    });
    md += `\`\`\`\n\n`;

    md += `\n*This report was autonomously generated by the Sentinel AI Agent System.*\n`;

    return md;
}
